box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxFile.java, box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxList.java, box-content-sdk/src/main/java/com/box/androidsdk/content/requests/BoxRequestsSearch.java
Includes:
Changes BoxList to always contain an entries field by default.
In BoxSearchRequest getLimit and getOffset now return Integers instead of String.
In BoxFile there is now a getFileVersion method.
=> Misc Fixes to content SDK

box-content-sdk/src/main/java/com/box/androidsdk/content/BoxException.java, box-content-sdk/src/main/java/com/box/androidsdk/content/auth/BoxAuthentication.java, box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxError.java, box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxSession.java, box-content-sdk/src/main/java/com/box/androidsdk/content/requests/BoxRequest.java, box-content-sdk/src/main/res/values/strings.xml
Better handle exceptions and add logic so that third party developers can customize authentication logic.
=> Custom authentication

box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxEnterpriseEvent.java, box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxEntity.java, box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxEvent.java, box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxFileVersion.java, box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxList.java, box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxRealTimeServer.java, box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxSession.java
Includes changing heirarchy of BoxEvent as well as a small change in BoxSession for user id.
=> Fix some misc issues in Content SDK for integration tests.

box-content-sdk/src/main/java/com/box/androidsdk/content/BoxException.java, box-content-sdk/src/main/java/com/box/androidsdk/content/auth/BoxAuthentication.java
=> Ensure expiresIn field is copied while cloning auth info.

box-content-sdk/src/main/java/com/box/androidsdk/content/auth/BoxAuthentication.java
Fix a bug where multiple sessions that fail at the same time will trigger multiple refreshes.
=> Fix a bug in auth logic.

box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxEvent.java
Fixed bug that the wrong type was being returned on #getType()
=> Exposed additional properties on BoxEvent

box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxList.java
- This ensures that we can use build in sorting methods for the list.
=> Update BoxList to extend from List instead of collection.

box-content-sdk/src/main/java/com/box/androidsdk/content/requests/BoxRequestCollectionUpdate.java, box-content-sdk/src/main/java/com/box/androidsdk/content/requests/BoxRequestItem.java
Exposed BoxRequestCollectionUpdate so that it can be subclassed in our private API
=> Made BoxRequestCollectionUpdate abstract class public

box-content-sdk/src/main/java/com/box/androidsdk/content/requests/BoxRequestsSearch.java
- This is to enable fields for Search request
=> Change Search request from BoxRequest to BoxItemRequest

box-content-sdk/build.gradle, box-content-sdk/src/main/java/com/box/androidsdk/content/BoxApiEvent.java, box-content-sdk/src/main/java/com/box/androidsdk/content/BoxApiFile.java, box-content-sdk/src/main/java/com/box/androidsdk/content/BoxApiUser.java, box-content-sdk/src/main/java/com/box/androidsdk/content/BoxConfig.java, box-content-sdk/src/main/java/com/box/androidsdk/content/requests/BoxRequestDownload.java, box-content-sdk/src/main/java/com/box/androidsdk/content/requests/BoxRequestsFile.java
Create new API to inform server on file preview, which include
it to recents list.
This commit partially revert the changes from 1cba2c7fcd210235a3a330a010be50d669fd7302
=> AND-7032 - Do not include thumbnail downloads to recents.

box-content-sdk/src/main/java/com/box/androidsdk/content/BoxApiRecentItems.java, box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxIteratorRecentItems.java, box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxRecentItem.java, box-content-sdk/src/main/java/com/box/androidsdk/content/requests/BoxRequestRecentItems.java
* Created two models BoxRecentItem and BoxIteratorRecentItems
* Created API class and request class to perform the operation
=> Perform GET Request on recents endpoint and create all the required models

box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxSession.java
As the task to authenticate can be pretty fast and it start to run
right on the authenticate call, setting a listener on the task after
the call to authenticate might be too late.
=> AND-7135 - Allow to set a listener on authenticate request

box-content-sdk/src/main/java/com/box/androidsdk/content/BoxConstants.java
This change should prevent any clash on parameters
=> AND-7354 - Use "box" prefix on custom parameters

box-content-sample/src/main/java/com/box/androidsdk/sample/MainActivity.java
Update sample to work with api 23.
=> Update Sample to api 23

box-content-sdk/src/main/java/com/box/androidsdk/content/BoxApiFile.java, box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxRepresentation.java, box-content-sdk/src/main/java/com/box/androidsdk/content/requests/BoxRequestsFile.java
This commit should update the BoxRepresentation class to be up-to-date
with the latest spec.
Also added a new request to download the representation thumbnail
=> JARVIS-404 - Include API to retrieve file thumbnail representation

box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxSession.java
During EMM launch, the logout and authenticate could run at a very
close time.
Both requests use the synchronized block for mSession object, and the
authenticate processing does not uses the appropriate mechanism of
waiting without holding the mSession lock (wait()).
The scenario above can lead into a deadlock, and this commit should fix
that.
=> AND-8114 - Avoid deadlock on EMM launch due to BoxSession lock

box-content-sdk/src/main/java/com/box/androidsdk/content/auth/BoxAuthentication.java
=> Add createdAt as a field

box-content-sdk/src/main/java/com/box/androidsdk/content/BoxException.java, box-content-sdk/src/main/java/com/box/androidsdk/content/requests/BoxRequestDownload.java
Add a new type of BoxException to report if downloads fail sha1 expectancy.
=> Add corrupted exception

box-content-sdk/src/main/java/com/box/androidsdk/content/auth/AuthenticatedAccountsAdapter.java
- getItemViewType() should return values in the range,
0 to getViewTypeCount() - 1
=> Fix off-by-one error for account switcher

box-content-sample/src/main/java/com/box/androidsdk/sample/MainActivity.java
- clearing the adapter needs to be done on the UI thread
=> Fix logging-out all accounts in sample app

.travis.yml, box-content-sdk/build.gradle, box-content-sdk/src/main/java/com/box/androidsdk/content/BoxConfig.java, build.gradle, gradle/wrapper/gradle-wrapper.properties
- contains various bug fixes and stability improvements
- update gradle version used
=> Release SDK version 4.2.3

box-content-sdk/src/main/java/com/box/androidsdk/content/utils/SdkUtils.java
To fix a bug in toastSafely method in SdkUtils file
=> Reversed conditional operator for AND-9320

box-content-sdk/build.gradle, box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxCollaboration.java, box-content-sdk/src/main/java/com/box/androidsdk/content/utils/SdkUtils.java, box-content-sdk/src/main/java/com/box/androidsdk/content/views/BoxAvatarView.java, box-content-sdk/src/main/res/drawable/initials_count_thumb_background.xml, box-content-sdk/src/main/res/layout/boxsdk_avatar_item.xml, box-content-sdk/src/main/res/values/attrs.xml
Changes are made to change the look of BoxAvatarView and make invite_email as one of the fields returned inside BoxCollaboration.
=> Box avatar view collaborations changes

box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxIterator.java, box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxOrder.java, box-content-sdk/src/main/java/com/box/androidsdk/content/requests/BoxRequestsFolder.java
Adds sorting and marker based paging functionality for get folder items.
=> Adds support for sorting and marker based pagination.

box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxClassification.java, box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxFile.java, box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxFolder.java, box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxItem.java, box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxJsonObject.java
This PR add BoxClassification object and classification field to items to support Shield Classification.
=> Changes to Support Shield

box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxClassification.java
This makes the class public so that it can be used from other packages
=> make the class public

README.md
Related to https://github.com/box/box-java-sdk/pull/1129
=> docs: add note about migrating to Java SDK
