box/box-android-sdk

README.md
Users migrating from the `box-android-content-sdk` might be confused as to why they cannot get the latest changes. This makes it clear that the SDK is published at a different location.
=> Add maven artifact information

README.md
As per note on https://developers.box.com/docs/ that "we will no longer be updating this current page after April 22, 2015".
=> Update Content API Docs link to current URL

box-content-sdk/src/main/java/com/box/androidsdk/content/BoxApiFile.java, box-content-sdk/src/main/java/com/box/androidsdk/content/requests/BoxRequest.java, box-content-sdk/src/main/java/com/box/androidsdk/content/requests/BoxRequestDownload.java, box-content-sdk/src/main/java/com/box/androidsdk/content/requests/BoxRequestsFile.java
* Refactored DownloadThumbnail to account for thumbnail format based on size. 
* Fixed and deprecated request constructors not exposing the file id
=> Thumbnails

box-content-sdk/src/main/java/com/box/androidsdk/content/utils/ProgressOutputStream.java
Fixes downloaded files not being renamed properly after completion when progress listener is attached
=> Fixed flush for downloads 

box-content-sdk/src/main/java/com/box/androidsdk/content/requests/BoxRequestUpload.java
BoxRequestUpload extends from BoxRequest and not BoxRequestItem. Due to
this, we are not sending fields with it and hence not gettings permissons
and other required properties.
- Fixed it by extending from BoxRequestItem
=> Fix file permissions on upload file

box-content-sdk/src/main/java/com/box/androidsdk/content/auth/BoxAuthentication.java
This is a fix for Box Android SDK issue 135 (https://github.com/box/box-android-sdk/issues/135). When a authentication request triggers an exception, we remove the task from BoxAuthentication.mRefreshingTasks in the catch block before re-throwing the exception. If this is not done, then subsequent requests will all fail because a task already exists which will return the failed result.
=> Fix for Box Android SDK issue 135

box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxIterator.java
- We were using write instead of writeInt. If the value was 0, it was
being interpreted as something else and readInt was failing.
=> Fix bug in box iterator serialization

box-content-sdk/src/main/java/com/box/androidsdk/content/BoxException.java, box-content-sdk/src/main/java/com/box/androidsdk/content/auth/BoxApiAuthentication.java, box-content-sdk/src/main/java/com/box/androidsdk/content/auth/BoxAuthentication.java, box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxSession.java, box-content-sdk/src/main/java/com/box/androidsdk/content/requests/BoxRequest.java
Better handle error conditions which can cause user to get logged out. Also fixes a bug where user can immediately get logged out after logging in due to a previous unauthenticated request waiting.
=> HandleUnauthorizedScenarios

box-content-sdk/src/main/java/com/box/androidsdk/content/requests/BoxRequestDownload.java
- In case the response is encoded, ensure it is decoded before writing to
a file
=> Fix the text file corruption bug

box-content-sdk/src/main/java/com/box/androidsdk/content/requests/BoxRequestMultipart.java
According to https://docs.box.com/reference#upload-a-file, the file bytes should come after the JSON for best performance.
=> Fix the multipart request form order

box-content-sdk/src/main/java/com/box/androidsdk/content/BoxApiFile.java, box-content-sdk/src/main/java/com/box/androidsdk/content/BoxApiUser.java, box-content-sdk/src/main/java/com/box/androidsdk/content/requests/BoxRequestDownload.java, box-content-sdk/src/main/java/com/box/androidsdk/content/requests/BoxRequestsFile.java
The server needs to differentiate when a file is accessed only to be available
for later access from the real file previewing. So a new parameter was made available
for that.
=> AND-7032 - New parameter for offline access only

box-content-sdk/src/main/java/com/box/androidsdk/content/requests/BoxRequestRecentItems.java
The default limit of 100 is set for GET recent items.
=> AND-7076: Set limit for GET request for recents endpoint

box-content-sdk/src/main/java/com/box/androidsdk/content/utils/BoxDateFormat.java
On older devices, the java6 library could not handle the + sign
as the initial character when parsing a string into an int.
This change should fix that for all versions.
Also fixed the minutes offset from timezone.
=> AND-7117 - Fix integer parsing when starts with + sign

box-content-sdk/build.gradle, box-content-sdk/src/main/java/com/box/androidsdk/content/BoxApiUser.java, box-content-sdk/src/main/java/com/box/androidsdk/content/requests/BoxRequestsFile.java
- Added Support Annotations library to use @StringDef annotation as a replacement for enums
(https://developer.android.com/studio/write/annotations.html#enum-annotations)
=> Provide support to fetch user avatars of different types (eg. small, large, profile)

box-content-sdk/src/main/java/com/box/androidsdk/content/requests/BoxRequestMultipart.java, box-content-sdk/src/main/java/com/box/androidsdk/content/requests/BoxRequestsFile.java
Fixes a bug where multiput files for large uploads fail due to erroneous int to long conversion.
Also improves performance of such logic by reusing byte buffer instead of creating new ones.
=> Fix multi put upload for large files

box-content-sdk/src/main/java/com/box/androidsdk/content/BoxException.java
Adds another Java exception that should be interpreted as a network error.
=> Add another error case for classifying as network error.

box-content-sdk/src/main/java/com/box/androidsdk/content/auth/BoxAuthentication.java
- createFromJson in BoxImmutableAuthenticationInfo is called in the
object's normal lifecycle (from BoxJsonObject parent). Removing this
logging to clean up logs
=> Remove error logging for createFromJson in auth

box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxCollaborationItem.java
Adds a new field and getter for default invitee role which will allow UI to show the best default per file or folder item when inviting collaborators.
=> Add a field and getter for default invitee role

box-content-sdk/src/main/AndroidManifest.xml, box-content-sdk/src/main/java/com/box/androidsdk/content/utils/BoxContentProvider.java
Add ContentProvider initialization step that will help solve case where Context reference is not present in BoxConfig field (issue: box/box-android-preview-sdk#23)
Depends on https://github.com/box/box-android-sdk/pull/405
=> Context ContentProvider

box-content-sdk/src/main/java/com/box/androidsdk/content/requests/BoxRequestItem.java
Fixes a bug where when duplicating a request item via the special constructor id and mHintHeader can be lost.
=> Fix a bug where some requestitem information is lost.

CHANGELOG.md, box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxFile.java, box-content-sdk/src/main/java/com/box/androidsdk/content/models/BoxFileVersion.java, box-content-sdk/src/test/java/com/box/androidsdk/content/models/BoxFileTest.java
Added the uploader display name field to the `BoxFile` and `BoxFileVersion` models
=> Add support for the uploader display name field for Files and File Versions

CHANGELOG.md, box-content-sdk/src/main/java/com/box/androidsdk/content/requests/BoxRequest.java, box-content-sdk/src/test/java/com/box/androidsdk/content/requests/URLValidationTest.java, build.gradle
Added path parameter sanitization so no relative paths can be passed (i.e. `/../`). I did not include this logic in `buildURL()` in `BoxRequest` because though this is used for most requests, it is not the only `buildURL()` method. There are others in the SDK that are used for other requests. So I would have to include the logic in multiple methods if I chose the `buildURL()` route. The only method all requests used was the `send()` method in `BoxRequest`, so I included the sanitization logic here.
=> Add path parameter sanitization

CHANGELOG.md, box-content-sdk/src/main/AndroidManifest.xml
- https://github.com/box/box-android-sdk/issues/439
- Fix cross-app scripting vulnerability in `OAuthActivity`
- Google Play Store's recommends an option to fix this security vulnerability, which is to not export the affected WebView Activity (`OAuthActivity`). See here for more details on the recommendations: https://support.google.com/faqs/answer/9084685?hl=en-GB
- [Here is the original change](https://github.com/box/box-android-sdk/pull/34) where `OAuthActivity` was initially exported. The intention of the original fix was to prevent OAuthActivity from being recreated upon screen reorientation. This fix is achieved with the addition of `android:configChanges="orientation|screenSize"`, whereas exporting the activity is not required.
- Verified that OAuthActivity is not being recreated …
=> Fix cross-app scripting vulnerability
